environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.8"
    - nodejs_version: "5.12"
    - nodejs_version: "6.11"
    - nodejs_version: "7.10"
    - nodejs_version: "8.4"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set shrinkwrap false
  - npm rm --save-dev connect-redis
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
  - npm run lint
version: "{build}"
